### ISSUE TITLE
Implement filtering on feed(s)

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#102]
All post feeds need to have filters on them.  You should be able to filter by:

- response to assignment or free post
- media_object_type ( text, image, video, audio )

Low priority, but could be nice:

- date range?

@Nolski what kind of effort do you think this is?  Do you want to tag team it some time this week together?

**Comment by Nolski** [comment]
Filters are common in angular. Date range might be a bit more difficult but I'd be surprised if there wasn't already an angular module written for it 

https://docs.angularjs.org/api/ng/filter/filter

**Comment by thequbit** [comment]
Very cool.   Let's ignore date picker for now.

**Comment by Nolski** [comment]
Resolved by #108
