### ISSUE TITLE
View post modal doesn't work in firefox

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#116]
With respect to #113 , the modal doesn't show up in Firefox, it just refreshes the feed.  Does work in Chrome and IE II.

**Comment by thequbit** [comment]
Firefox 35.0.1

**Comment by Nolski** [comment]
Just viewed in Firefox 35.0.1 (and it seems to work fine for me). This is running the code in PR #121

**Comment by thequbit** [comment]
This bug was squashed somewhere along the way, and i think it was me not getting the latest code (cacheing issue).
