### ISSUE TITLE
URL not infront of media when writing story

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#118]
the URL ends up being /media/<media_file>, with no root URL.

**Comment by Nolski** [comment]
I'm not quite sure what this issue means.

**Comment by Nolski** [comment]
ping (previous comment)

**Comment by thequbit** [comment]
Ahh, sorry.  So if you have a collection loaded in the 'Write Article' page, and click on it, the URL that it copies to the click board is not 'complete'.  It is missing the 'https://yellr.net/' portion.

When I click, and then Ctrl-V, I get:

    ![](/media/d10ec642-0aa4-445e-af6f-09c5fe313ccc.jpg)

When I would expect to get:

    ![](https://yellr.net/media/d10ec642-0aa4-445e-af6f-09c5fe313ccc.jpg)

The ROOT_DOMAIN could be a configurable item in the server, or on the front-end if you would like.  The HTML that is generated from this looks like this:

    <p><img alt="" src="http://yellr.mycodespace.net/media/388b2126-c73e-426a-8b67-6bcd34d4bb30.jpg" /></p>

... which is what I expect, HOWEVER, the Android app does not interpret this correctly, and does not display the images (but if `https://yellr.net/` is included, it works as expected).

This does, however, make testing difficult ...

Thoughts?

**Comment by Nolski** [comment]
Ah I see. I did this on purpose. This assumes that the images resides on the same server that the content is being served from. I think this is appropriate since I don't see why the image would be on a different server than the content which the image is for. 

If the app is rendering HTML pulled down from yellr.net shouldn't it understand that the images are from yellr.net as well?

**Comment by thequbit** [comment]
It isn't pulling down the HTML from yellr.net, it's pulling down a json
response that has rendered HTML within it.  This *could* be changed if
needed, and certainly may change once we get more of the 'store-front'
completed.

I can over-come this on the android side with some .replace() or regex for
the time being.  Let's keep it open until after the v0.1.0 milestone.

On Fri, Mar 6, 2015 at 3:25 PM, Mike Nolan <notifications@github.com> wrote:

> Ah I see. I did this on purpose. This assumes that the images resides on
> the same server that the content is being served from. I think this is
> appropriate since I don't see why the image would be on a different server
> than the content which the image is for.
>
> If the app is rendering HTML pulled down from yellr.net shouldn't it
> understand that the images are from yellr.net as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/118#issuecomment-77629233>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
I'm closing this.  The more I think about it, the more I think you are correct @Nolski that any other client should be responsible for fixing the URL.
