### ISSUE TITLE
Create Preview Posts API Endpoint

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#12]
Create API endpoint to get smaller version of user posts with smaller images and just a preview (first 140 characters?) of the text, not the whole text.

**Comment by thequbit** [comment]
Just the images will be resized.   This will also be where any video has a reference preview frame generated. No need to shorten text posts.

**Comment by thequbit** [comment]
Thoughts on this?  What was your objective?

**Comment by Nolski** [comment]
This seems about right. Do you have any examples of some resized images? (some pictures taken with your phone will probably work fine).

**Comment by thequbit** [comment]
I'll get some examples to ya asap.

--
Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

This seems about right. Do you have any examples of some resized images?
(some pictures taken with your phone will probably work fine).

—
Reply to this email directly or view it on GitHub
<https://github.com/hhroc/yellr-server/issues/12#issuecomment-70515945>.

**Comment by thequbit** [comment]
resizing to 450 pixels wide rather than 300.

**Comment by thequbit** [comment]
Implemented.  Let me know if that works for you.

**Comment by Nolski** [comment]
Yup it does. Tag this issue in the PR and I'll close it.

**Comment by Nolski** [comment]
Pulled the changes down and this is resolved.
