### ISSUE TITLE
Implement 'save story for later' feature.

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#120]

**Comment by Nolski** [comment]
This is already built into epic editor. Unless you want the story saved on the server, rather than LocalStorage.

**Comment by thequbit** [comment]
My thought here was we could have a field within the table for 'published'.  This way, you could place stories in a 'staging' mode.  This also falls in line with how WXXI already does their editing flow (a story is placed into Drupal and then is edited and approved by someone else, and then published).

It would be the same end point, just simply setting a new field of 'published' to false.

Thoughts?

**Comment by Nolski** [comment]
Yeah, I think we need to rethink the whole UX for story creation. That entire part of the moderator site is kind of in a sad state ATM.

What I'm thinking is something like having a "Create Stories" or something type of page which lists all drafts and has a new story button. That drops you into the whole editing interface (which needs an overhaul) and allows you to do the editing stuff.

Then we will have a "View Stories" where you can edit each story using the same edit UI

**Comment by thequbit** [comment]
:+1:

Makes sense to me!

**Comment by thequbit** [comment]
No longer applicable with server re-write.  Closing.
