### ISSUE TITLE
refresh button on post list

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#126]
Need a refresh button.  Also, re-clicking the 'raw-feed' should reload the list.

**Comment by Nolski** [comment]
Doesn't the browser already do this?

**Comment by thequbit** [comment]
There are really two things here:

  1) Refresh button

I think this is a good idea, as it is very clear what it's going to do.  Perhaps a 'load latest posts' button at the top, that would pull down the posts since you loaded the page?

  2) Clicking the 'raw-feed' nav link should refresh the page

I think this is pretty straight forward, and should be implemented.  Is there a technical challenge to do that with angular?

**Comment by Nolski** [comment]
Yeah it's simple to do. (At least number 1 is) but I don't see the point. When I look at facebook or twitter, or any other feed based web application, they don't have a big refresh button. The user simply refreshes the page. I know twitter will have a button show up once new tweets are available but that's an entirely different feature and requires a more complex solution.

**Comment by thequbit** [comment]
Hu, i always hit the 'home' button on facebook to refresh ... which I suppose is like hitting 'raw-feed' again for us?

I guess i try not to refresh pages when i'm on them, as i feel like most websites are rather delicate when it comes to state, ha.

Thoughts on just doing 2) then?

**Comment by Nolski** [comment]
Sure. Let's definitely leave this open for doing 2) and we can come back to this if we want to have a more page based way of refreshing.

**Comment by thequbit** [comment]
:+1:

On Fri, Mar 6, 2015 at 2:50 PM, Mike Nolan <notifications@github.com> wrote:

> Sure. Let's definitely leave this open for doing 2) and we can come back
> to this if we want to have a more page based way of refreshing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/126#issuecomment-77623725>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits
