### ISSUE TITLE
Make default admin password on backend double hashed

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#13]
To prevent MITM attacks for users with poor/no SSL certs we want to hash the users password prior to sending it over to the server. I am using SHA256 to hash the password so in our backend database it would be easiest to have the password be `sha256(sha256(password))` instead of what it currently is (`sha256(password)`) since that way it will reflect the kind of password our front end will be passing it.

**Comment by thequbit** [comment]
Implemented.
