### ISSUE TITLE
Nothing shows up in the collection list on 'create story' page if the post does not have an image

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#130]
We need a way to display a post even if it's text ...

**Comment by Nolski** [comment]
Can you explain the situation where we need to copy paste text posts into the editor? This doesn't really seem like something that journalists will really need when writing a story.

**Comment by thequbit** [comment]
I would expect this to be similar to embedding a tweet in a story.   Some kind of border with shadow and a different background color than the default page (which is #eeeeee).

**Comment by Nolski** [comment]
Are you sure? I could see this causing issues since a tweet has a very limited character amount where-as a post can be any length and have multiple pictures, videos, text paragraphs etc. I think it would be very likely that the author will simply want to embed a picture.

**Comment by thequbit** [comment]
THis is a great example of something you would want to embed (taken from our production instance):

![](http://i.imgur.com/c07Zuxk.png)

I say we display it in the list with a limit number of characters (128?).  Just because a test-only post *could* be long, doesn't mean we shouldn't support embedding it.

I would like to see any text that is included with an image update displayed below it (or somewhere around it), and an option to just embed text.

**Comment by Nolski** [comment]
I agree that would be handy, and we should include the ability to embed posts. I'm just not sure where it lies within the priorities of the user's experience. Would a journalist rather be restricted to being able to only embed posts (in the format that we think is right) or would they rather be able to copy/paste content out of the post and into the story?

**Comment by thequbit** [comment]
hu, interesting.  I guess I had not though of that flow before.  I think this is a great conversation to have with some journalists.  I'll see if I can pull Matt Leonard into the conversation.

**Comment by thequbit** [comment]
What did we finally decide on this one?  Are we going to put something in as maybe a quote?

**Comment by Nolski** [comment]
Hm, I don't think that we did. We can talk about this real quick tonight.

**Comment by Nolski** [comment]
resolved in #218
