### ISSUE TITLE
Get open street maps to serve the map tiles over https

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#152]
Not sure why it isn't at the moment, but the tiles should be served over https just like the rest of the moderator site (to prevent mixed-content warnings).

**Comment by Nolski** [comment]
Looks like open layers requires us to host it ourselves if we want to serve the tiles over SSL https://github.com/openlayers/openlayers/issues/1025

**Comment by thequbit** [comment]
Ahh,  yes I agree we should host all of our Javascript.   I was referring to the actual tile images,  not the openlayers library.  It may be as simple as adding the s to http...

**Comment by Nolski** [comment]
OpenLayers is where we load our javascript from. That's the issue.

**Comment by thequbit** [comment]
Closed with #154, closing.
