### ISSUE TITLE
Implement 'post viewed' registration

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#165]
There is an end point that registers that a post was viewed:

https://github.com/hhroc/yellr-server/wiki/Admin-API-Documentation#adminregister_post_viewjson

This should be called when a post is viewed (when the 'View Post' button is pressed).  This gives the client a notification that their post is being viewed by someone (a nice method of feedback).

**Comment by Nolski** [comment]
This was implemented in #205

**Comment by thequbit** [comment]
Nice.   I just need to get the notifications working correctly to push the the app.  Hope to get to those this week,  but if it's not solid by tomorrow I don't think I want to push to the play store before the conference.
