### ISSUE TITLE
Create api endpoint for listing and adding organizations

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#166]

**Comment by thequbit** [comment]
Added in PR #170.

Get Organizations:
https://github.com/hhroc/yellr-server/wiki/Admin-API-Documentation#adminget_organizationsjson

Add Organization:
https://github.com/hhroc/yellr-server/wiki/Admin-API-Documentation#adminadd_organizationjson

**Comment by thequbit** [comment]
Closed in #170.
