### ISSUE TITLE
get_my_collections return number of posts within collection as part of result

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#18]
Would it be possible to return the number of posts for each collection within the result of this API call? https://github.com/hhroc/yellr-server/wiki/API-Documentation#adminget_my_collectionsjson

**Comment by thequbit** [comment]
Yup.  Will implement and update docs after Lunch.

On Wed, Jan 7, 2015 at 10:45 AM, Mike Nolan <notifications@github.com>
wrote:

> Assigned #18 <https://github.com/hhroc/yellr-server/issues/18> to
> @thequbit <https://github.com/thequbit>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/18#event-215351201>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
response now includes 'post_count' field.

updated docs:
https://github.com/hhroc/yellr-server/wiki/API-Documentation#adminget_my_collectionsjson
