### ISSUE TITLE
Make change_password endpoint take both old and new password

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#181]
The change_password endpoint takes only one password which means if someone leaves their website open in their browser or something like that, the old password/new password functionality is kind of pointless.

I would suggest having a second parameter which is the old password as well and have the check on the server side.

**Comment by Nolski** [comment]
Also It might be a good idea to just remove the `username` field and have it do it for the user making the request.

**Comment by thequbit** [comment]
Marking as low priority for the moment, but I'll get to it.

**Comment by Nolski** [comment]
Alright. Not sure if this really needs to be on this milestone anyways. Feel free to remove if you think it's appropriate.

**Comment by thequbit** [comment]
Closed with #214.
