### ISSUE TITLE
Add a geo marker on the tiles 

### ISSUE THREAD

**Issue by evefrohm** [hhroc/yellr-server#187]
Add a geo marker with a link to the map and an approx. area 

e.g. "Whereabouts: South Wedge"

**Comment by thequbit** [comment]
This might be a bit tough to get down to neighborhood level at first,   but we can definitely do zipcode and/or town level.

**Comment by thequbit** [comment]
Circling back on this, I think that this would be possible to do on a county or _maybe_ a town level with some static files and fancy javascript, but may be diminishing returns.  Going to close this now, since we're going to implement the mapping of posts per #314
