### ISSUE TITLE
Add a text prompt when adding a geofence

### ISSUE THREAD

**Issue by evefrohm** [hhroc/yellr-server#188]
Add a text prompt when adding a geofence
e.g. “drag your cursor around the area you would like to geographically target"

**Comment by thequbit** [comment]
@Nolski and I talked about this at some point.   The entire geo fence flow needs to be improved.   I did the original screen,  so I'll take this on.

**Comment by thequbit** [comment]
This is a duplicate of #74, however we determined that it 'should be simple enough to just figure out'.  I am going to close #74 and keep this one open, since I think there does need to be a change.
