### ISSUE TITLE
Assignments no longer work, due to questions not being sent to the server

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#219]
@Nolski the create_question.json end point is never called when you create an assignment.

**Comment by Nolski** [comment]
Looks like the token somehow stayed in there. Good catch @thequbit

**Comment by thequbit** [comment]
The power of working in a team :).

On Thu, Mar 19, 2015 at 1:58 PM, Mike Nolan <notifications@github.com>
wrote:

> Closed #219 <https://github.com/hhroc/yellr-server/issues/219>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/219#event-259675877>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits
