### ISSUE TITLE
User data not showing on refresh

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#238]
This could be solved by having check_logged_in return the user info along with the rest of the data. @thequbit could you do this?

**Comment by thequbit** [comment]
This look okay?

    {
        "username": "system",
        "first_name": "SYSTEM",
        "last_name": "USER",
        "fence": {
            "bottom_right_lat": -90,
            "top_left_lng": -180,
            "top_left_lat": 90,
            "bottom_right_lng": -180
        },
        "success": false,
        "organization_id": 1,
        "organization": "Yellr",
        "logged_in": true
    }

**Comment by Nolski** [comment]
Yup. This is exactly what I was looking for!

**Comment by Nolski** [comment]
I think this has been fixed from a PR a while ago? Can't reproduce anymore

**Comment by thequbit** [comment]
I'm happy.  Closing.
