### ISSUE TITLE
Create New Assignment Form

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#25]
So this page is going to have a decent amount of functionality since you will need to:
- Create an assignment (and eventually set a geo-location bounds for it)
- Create any amount of questions of whatever types we offer (multiple choice, full text, etc).
- Add tags and any other meta-data content that we may need

So what I am thinking is to have multiple sub pages that you have to complete to create an assignment. This should be fairly easy to do in angular. Airbnb did something similar for their apartment listing form.

![screen shot 2015-01-09 at 11 20 53 am](https://cloud.githubusercontent.com/assets/2600677/5682916/a4ee0200-97f1-11e4-83c4-8277847d3e91.png)

Notice the checks next to the form parts. Upon submission we just make sure each form part is complete prior to submitting.

![screen shot 2015-01-09 at 11 20 09 am](https://cloud.githubusercontent.com/assets/2600677/5682915/a4ed2aa6-97f1-11e4-835d-737b8c6ebbca.png)

@thequbit what do you think of this? Anything that I'm missing out on?

**Comment by thequbit** [comment]
Does this flow make sense for the pages?

- Create Assignment
- Select language, and define question (and answers if multiple choice)
    - Define additional Questions in different languages if needed/wanted.
- Define geo-fence
- Publish.

**Comment by Nolski** [comment]
Yup that sounds good to me.

**Comment by thequbit** [comment]
Cool Cool.  I'll let you figure out the details of implementation, but I think those four pages make the most sense to me.

**Comment by Nolski** [comment]
implemented
