### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by evesoleil** [hhroc/yellr-server#277]
Any plans to make the desktop version responsive? Also never thought about this until now but how does the app look on tablets?

**Comment by thequbit** [comment]
Hi @evefrohm !

So yellr.net/local isn't _too_ bad for responsiveness.  I admit .. it's not awesome.  Is that what you were referring too?  Or were you talking about the moderator interface?

**Comment by evesoleil** [comment]
@thequbit yes I was referring to the moderator interface! I think the yellr.net/local one is okay for now

**Comment by thequbit** [comment]
We're going to only be targeting desktop for the moderator site, not mobile ( a mobile app will be available in the (far) future I would think ...

Going to close this for now since it's a wont-fix.
