### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by evesoleil** [hhroc/yellr-server#279]
Side bar has some styling issues. Need some padding on the right and general cleaning up. 

Also when you go to "Create assignment" the text on the sidebar on that page is getting cut off and is also confusing. Are they supposed to be page guides to indicate where you are in the process or are they actual buttons? "Publish" is currently in the middle of the three, it should probably come after creating the geofence or should at the bottom of the actual page as a button might be more intuitive.

**Comment by evesoleil** [comment]
This is for the Moderator interface BTW

**Comment by thequbit** [comment]
I believe all of these have been resolved.
