### ISSUE TITLE
(Security) Keep token in session rather than localStorage

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#29]
Currently we are keeping our authentication token as a variable and storing it in local storage. The issue here is that localStorage is a global object that all websites have access to, so any website that wants can have access to the token that the user uses to log into the admin console.

Instead I think it would be a better idea to use session variables on the server to authenticate a user.

@thequbit what do you think?

**Comment by thequbit** [comment]
Do you have a reference to the statement about localstorage being seen by all websites?  I was under the impression that it is site specific ...

I can implement the session variable, however the nice part about keeping it as a cookie or localstorage is that you don't have to log back in after a time-out, and it allows for much easier scalability.  If we're load balancing then we need to somehow replicate sessions across all pyramid instances ... that's a bit outside of my wheelhouse.  By keeping it on the client, and sending it as a GET parameter, we get around the scaling issue nice and simply.

The token is large enough, and unique enough that it's unlikely to be guessed, and everything will be sitting on https.  I don't see an issue keeping things they way they are ... that is assuming that I am correct that localstorage is sight-specific, and not as you are stating.

**Comment by Nolski** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#Reference
"The following are global objects that exist as properties of every window object. This means that they can be accessed as sessionStorage or window.sessionStorage."

The issue isn't someone guessing the token is that if the user visits their website they can just obtain it. I'm not very familiar but the concepts of sessions and multiple server instances are not new and I would be surprised if there isn't a way to have them work together.

**Comment by thequbit** [comment]
I'm not gonna lie, that seems very stupid to me to make localStorage global across all sites ... but I'm sure there was a reason for doing it that way.

> The issue isn't someone guessing the token is that if the user visits their website they can just obtain it. I'm not very familiar but the concepts of sessions and multiple server instances are not new and I would be surprised if there isn't a way to have them work together.

Don't disagree there, it's just outside the scope of what I know and am familiar with.

Referencing this doc: http://nginx.org/en/docs/http/load_balancing.html (scroll down to the 'Session persistence' section), it looks as though there is not a good way to share sessions across instances.  Nginx's solution is to enable ip hashing to ensure that an IP always goes to the same server instance.

I'll look into the session solution on my end ... keep going with the localStorage for the moment so I'm not blocking you.

**Comment by thequbit** [comment]
Per the pyramid docs, it doesn't look too terrible.

http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/sessions.html

It's going to take me a few hours to get this implemented, and it will be a bit of a change as to how authentication works (since we won't be passing the token around as a get param any more).  Do you want me to work on this now, or later?  is there something else that is higher priority?

**Comment by Nolski** [comment]
I think it would be a good idea to get this done before we use it in production  and other people start using it but I don't think it's so immediate that we need it done within the next few days or anything like that.

**Comment by thequbit** [comment]
I'll push it to the back burner for the moment, and work to implement it when i have a good stretch of a few hours to focus.

Thanks for doing the leg work on researching that!

**Comment by Nolski** [comment]
Ping - I think we should prioritize fixing this before we deploy to WXXI. I think we can agree that this is a critical security bug and it seems to be causing issues elsewhere as well.

**Comment by thequbit** [comment]
Here you are sir:

https://github.com/hhroc/yellr-server/pull/125

Checks for token in the GET, and if doesn't exist, goes for the session.  Let me know how it works for ya, and we can pull all of the token stuff out of the moderator side of things.

**Comment by thequbit** [comment]
Implemented.  Closing.
