### ISSUE TITLE
assignments do not have language associated with them, just questions

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#34]
On the create assignments subpages, it is the question that has the language associated with it, not the assignment.  The assignment is the container, and is always in English (because the moderator page (for he moment) is all in English).  The questions are what are in different languages.

**Comment by thequbit** [comment]
Implemented.  Each question now has a language, rather than the assignment.

**Comment by Nolski** [comment]
![screen shot 2015-01-23 at 3 02 14 pm](https://cloud.githubusercontent.com/assets/2600677/5881701/da5d00f6-a310-11e4-8d91-9be6cf82caab.png)
