### ISSUE TITLE
Server requires user to have imagemagick installed

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#41]
There isn't really any documentation for this here and is currently preeeeetty difficult to debug.

https://github.com/hhroc/yellr-server/blob/master/yellr-serv/yellrserv/client_views.py#L728

```python
try:
    ...
    subprocess.call(['mogrify', '-strip', temp_file_path])
    ...
except:
    pass
```
ends up just sending the user 
```json
{ "success": false }
```

**Comment by Nolski** [comment]
This is fixed by installing imagemagick and adding it to the user's PATH but I think it would be good to maybe add some additional error handling for this case.

**Comment by thequbit** [comment]
Yup,  you're correct.   That was my bad -  sorry about that.   Hope it didn't burn too much time for you. 

I'll work on updating the README for the server.

**Comment by thequbit** [comment]
Added to readme.
