### ISSUE TITLE
Adding Image Post to Collection doesn't seem to work?

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#44]
So here is what I did to reproduce this error.

I have an image post with post_id of 16. I have a collection with collection_id of 1. It already has a text post in it. (This is all using my HTTP client).

I call `http://localhost:5002/admin/add_post_to_collection.json?token=77b32db7-082a-4317-a12f-885a2a6adda2` with `post_id: 16` and `collection_id: 1`. 

I then call `http://localhost:5002/admin/get_collection_posts.json?token=77b32db7-082a-4317-a12f-885a2a6adda2&collection_id=1` and the post that I added does not show up.

**Comment by thequbit** [comment]
Thanks for putting the steps together.   I'll look into this now and report
back what I come up with.   The teats do add multiple posts to a collection
and check that they return (and they do),  so not sure what's up.

Do the posts that you are working with all have mediaobjects or are they
mixed with just text as well?

--
Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by Nolski** [comment]
Every post that I have created has a media object of some sort. From my understanding text is wrapped in a media object of type text.

The issue is purely with posts that have an image media object which it looks like your tests don't cover.

**Comment by thequbit** [comment]
Alright,  I'll see what I can drum up with just media objects.   I have a
suspicion it's a join vs.  outterjoin issue.

--
Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
The post was being added correctly, however the sql query to pull them back out was incorrect.  I was comparing user_id to post_id.  Fixed in commit to my fork ( https://github.com/thequbit/yellr-server/commit/8dbc6ecf7f387e3179b90188a651773e00d64984 ).

We'll take a look tomorrow together to make sure it was the correct fix.

Also still working on redoing test framework to better cover these kinds of things.

**Comment by Nolski** [comment]
This seems to work now.
