### ISSUE TITLE
Implement view post page

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#54]
Need a page to actually view a post.  This page should display any media objects as well as any text with a post.  You should also be able to message a user from this page (note: we can hold off on the messaging thing).

You will also need to be able to add the post to a collection.

**Comment by thequbit** [comment]
was an issue with the sql alchemy call with get_post.json, fixed here:

https://github.com/thequbit/yellr-server/commit/5ddac60b6600d0a3f640cc90c5be495d7aa3c6ef

Should be ready to go.

**Comment by Nolski** [comment]
:+1:
