### ISSUE TITLE
Migrate away from mapbox to simple leaflet implementation

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#55]
We are relying on mapbox right now to do the geofence drawing.  We should migrate away from that since it needs an API key, which is a pain.

This is related to  #31.

**Comment by thequbit** [comment]
This seems like a slick library, that is way easy to use.

https://github.com/heyman/leaflet-areaselect/

@Nolski mind if I take this one on?  Looks to be a simple enough implementation to ease me into sass and angular.js.

Let me know!

**Comment by Nolski** [comment]
This looks awesome. Let me know if you run into anything or have any questions.

**Comment by thequbit** [comment]
Implemented custom solution since leaflet-areaselect just wouldn't work with our current libraries.

**Comment by thequbit** [comment]
Hold down ctrl and drag to make the box.  I think we should inform the user on how to do this with a pop-up.  Will open new issue for this.
