### ISSUE TITLE
Make /login POST

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#66]
Browser history caches login parameters through URL and servers often log GET parameters. This means that we would could be storing passwords in browser history and logs.

**Comment by thequbit** [comment]
I like it.  I'll migrate over to POST and submit a PR before Sunday.

On Fri, Jan 30, 2015 at 1:23 PM, Mike Nolan <notifications@github.com>
wrote:

> Assigned #66 <https://github.com/hhroc/yellr-server/issues/66> to
> @thequbit <https://github.com/thequbit>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/66#event-227700247>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
Implemented.

https://github.com/hhroc/yellr-server/pull/65
