### ISSUE TITLE
Inform user how to create geofence

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#74]
Geofence is created on the leaflet map by holding ctrl and dragging.  This is not obvious, and is not told to you anywhere.  need to inform the user that this is what they need to do.

Maybe a pop-up?

**Comment by Nolski** [comment]
Is the ctrl and dragging a leaflet-draw feature? From what I remember, you clicked a button.

**Comment by Nolski** [comment]
I see the PR now. 

This doesn't work on osx since ctrl+click is right click

**Comment by thequbit** [comment]
Well apple is stupid, so there.

But seriously, what's your thoughts on how to start and stop the drawing?
A button?


On Sun, Feb 1, 2015 at 11:10 PM, Mike Nolan <notifications@github.com>
wrote:

> I see the PR now.
>
> This doesn't work on osx since ctrl+click is right click
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/74#issuecomment-72404182>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by Nolski** [comment]
Yeah I'd say a button and cursor change.

**Comment by thequbit** [comment]
I've implemented something for this, however i'm still not super excited about it.  Will keep this open for the time being.

**Comment by thequbit** [comment]
Closing based on comments in #188.
