### ISSUE TITLE
If there aren't any posts, something should be displayed

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#77]
If an assignment doesnt have any posts responding to it yet, or a collection is empty, there should be something that says "nothing here yet, check back soon!" ... or something like that.

**Comment by thequbit** [comment]
Implemented in #78

**Comment by Nolski** [comment]
Screenshot pls

**Comment by thequbit** [comment]
Will post when back to the PC.  Very much so a placeholder.   It'd just h4 tag with text in it.

**Comment by thequbit** [comment]
Sorry for the delay on this.

Empty Raw Feed:
![](http://i.imgur.com/tgPgoQ4.png)

Looks like there is some CSS things to clean up with the right side bar not floating right.

Empty Assignments List:
![](http://i.imgur.com/44wRTSz.png)

Empty Collections List:
![](http://i.imgur.com/v3K2eoH.png)

If you're happy with that I'll merge PR https://github.com/hhroc/yellr-server/pull/81

**Comment by thequbit** [comment]
Closing with #81
