### ISSUE TITLE
Create 'create collection' page

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#79]
Should we also link to this on the right side?  What should the flow be?  A button on the 'view collections' page?

Whatever we do we should keep it consistant for assignments.

@Nolski I can take this one on if you would like, just let me know.

**Comment by Nolski** [comment]
I was thinking a button that pops up a modal form. I can take it on tonight or tomorrow when i get a couple of cycles but if you have free time and want to finish it feel free to assign it.

**Comment by thequbit** [comment]
Looks like the collection is created, however the modal is not closed.

**Comment by thequbit** [comment]
closed with #103
