### ISSUE TITLE
server_info.json endpoint returning 404 status

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-server#83]
http://yellr.mycodespace.net/server_info.json is returning 404.

**Comment by thequbit** [comment]
I believe this is to be expected as I think in the latest I pulled that end
point.   I'll check and update.

--
Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
I updated the docs to show deprecation.  We can bring this back later if we need it.  I would prefer to use nginx to host different versions of the api rather than match on server/client versions.  Closing for now.

**Comment by reustonium** [comment]
it's common practice to put the api version number right in the URI, that way you can still support people on an older API

e.g.
`https://yeller.mycodespace.net/v1/server_info.json`

**Comment by thequbit** [comment]
Yup, it will be like that when behind the nginx instance.  We'll proxy pass to the correct version of the app for each API version.  That is a layer above the pyramid application, and nginx (although actually load balancing on the server farm that mycodespace.net is running on) is not currently implementing any proxy passing.
