### ISSUE TITLE
Endpoints are confusing [Opinion Alert]

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-server#84]
the API endpoints don't follow typical RESTful guidelines.  As a consumer I'm used to seeing an endpoint represent a resource, not a method and resource.

e.g. the current API for getting messages
### Get Messages Endpoint
`get_messages.json?client_id=xxxxx`

This is fairly straight forward but much neater is
### RESTful Get Messages Endpoint
`messages/:client_id`
I know that I'm issuing a GET command, so why include it in the end-point name?

Where it get's confusing is the post endpoints, including the method and taking all the parameters in the URL get's ugly.
### Publish_post Endpoint
`publish_post.json?cliend_id=xxxxx&assignment_id=xxxxx&language_code=xx&title=xxxx&lat=xxxxx&lng=xxxxx&media_objects=xxxxxx`

### RESTful Posts Endpoint
`posts/`
the body of the request can be any good MIMEtype, `form-data`, `x-www-form-urlencoded`, etc

[This](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful) is a nice little guide on RESTful API design.

Thus ends my opinionated rant.

**Comment by thequbit** [comment]
publish_post.json and upload_media.json are both HTTP POST, not GET.  So you wouldn't put the parameters in the URL like that. 

We can discuss changes in nomenclature at a later date,  making changes like the ones you are suggesting are not hard in pyramid. 

Keep the suggestions coming,  all great feedback. I'll check out the link you posted.

**Comment by thequbit** [comment]
Fixed with re-write.  yay!

**Comment by reustonium** [comment]
awesome, I'm happy to see these changes made it in!

**Comment by thequbit** [comment]
A follow-up, here are the end points as they exist today in the `develop` branch.  A few more will need to be added, but we're getting close!

### Client REST end-points

[ GET ] - get's local assignments
`/api/assignments`

[ GET ] - get's local posts
[ POST ] - posts new post
`/api/posts`

[ POST ] - creates media object against a post
`/api/media_objects`

[ POST ] - votes on a post
`/api/posts/{id}/vote`

[ POST ] - flags a post
`/api/posts/{id}/flag`

[ GET ] - get's clients profile
[ PUT ] - updates a clients profile
[ DELETE ] - marks the client as deleted ( forgotten )
`/api/clients`

#### Admin Static HTML Pages

[GET] - Admin login page ( returns html )
`/login`

#### Admin REST end-points

[ GET ] - Check if logged in ( checks if token is valid in session cookie )
[ POST ] - Performs login with username and password
`/api/admin/login`

[ POST ] - Logs out ( invalidates token, and removes from session cookie )
`/api/admin/logout`

[ GET ] - Returns list of posts
`/api/admin/posts`

[ GET ] - Returns single post
`/api/admin/posts/{id}`

[ GET ] - Returns assignments list
[ POST ] - Creates new assignment
`/api/admin/assignments`

[ GET ] - Returns specific assignment
[ PUT ] - Updates specific assignment
`/api/admin/assignments/{id}`

[ GET ] - returns posts that are in response to assignment ( this might change to a query param on /api/admin/posts )
`/api/admin/assignments/{id}/responses`

[ POST ] - Create a new question
`/api/admin/questions`

[ PUT ] - Update a specific question
`/api/admin/questions/{id}`

[ GET ] - Get's user list
[ POST ] - Creates a new user
[ PUT ] - Updates user ( used for changing password )
[ DELETE ] - Removes a user
`/api/admin/users`
